### ISSUE TITLE
Does not work when reload the VScode

### ISSUE THREAD

**Issue by YordanPetrovDS** [PKief/vscode-copy-branch-name#4]
When i reload the vscode, the extension does not work. When i disable it and enable it again it works.

**Comment by princepolysports** [comment]
> When i reload the vscode, the extension does not work. When i disable it and enable it again it works.

same issue in 2024

**Comment by PKief** [comment]
Should be fixed with the new version 1.0.4 on the marketplace. Thanks for reporting.
